#!groovy

//homework2

properties([disableConcurrentBuilds()])

pipeline{
    agent any
    options{
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("First step: Build") {
            steps{//Using dockerfile from homework1
                echo "========Building image started========"
                dir('hm2/docker'){
                    sh 'docker build -t homework2:v0.1 . '
                echo "========Building image finished========"
                }
            }

        }
        stage("Second step: Deploy") {
            steps{
                echo "========Running image started========"
                dir('hm2/docker'){   
                    sh 'docker run --rm homework2:v0.1 '  
                echo "========Running image finished========"
                }
            }

        }
    }
}
